export const items = [
  {
    id: Math.random(),
    title: "وجبة عشاء ",
    des: "وصف الفطار",
    price: "40 جنيه ",
    category: "عشاء",
    imgURl: "download.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "120 جنيه",
    category: "غداء",
    imgURl: "download (2).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "90 جنيه",
    category: "غداء",
    imgURl: "download (3).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار ",
    des: "وصف الفطار",
    price: "90 جنيه",
    category: "افطار",
    imgURl: "download (4).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار ",
    des: "وصف الفطار",
    price: "50 جنيه",
    category: "افطار",
    imgURl: "download (1).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "100 جنيه",
    category: "غداء",
    imgURl: "hq720.jpg",
  },
];
