export const Items = [
  {
    id: Math.random(),
    title: "وجبة عشاء ",
    des: "وصف العشاء",
    price: "40 جنيه ",
    category: "عشاء",
    img: "download.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "120 جنيه",
    category: "غداء",
    img: "download (2).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "90 جنيه",
    category: "غداء",
    img: "download (3).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار ",
    des: "وصف الفطار",
    price: "90 جنيه",
    category: "افطار",
    img: "download (4).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار ",
    des: "وصف الفطار",
    price: "50 جنيه",
    category: "افطار",
    img: "download (1).jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ",
    des: "وصف غداء",
    price: "100 جنيه",
    category: "غداء",
    img: "hq720.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة الحلو ",
    des: "وصف الحلو",
    price: "100 جنيه",
    category: "الحلو",
    img: "download (5).jpg",
  },
];
